apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "false"
  name: tekton-insights
  namespace: rh-hms-tenant
spec:
  application: provisioning-backend
  params:
  - name: APP_NAME
    value: provisioning
  - name: COMPONENTS
    value: rbac sources-api sources-superkey-worker notifications-backend
  - name: COMPONENT_NAME
    value: provisioning-backend
  - name: IQE_PLUGINS
    value: provisioning
  - name: IQE_MARKER_EXPRESSION
    value: api and smoke
  resolverRef:
    params:
    - name: url
      value: https://github.com/RedHatInsights/bonfire-tekton.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/basic.yaml
    resolver: git
